//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schedule.data.erps.dictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_DUONGDUNG
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public string MaDuongDung { get; set; }
        public string TenDuongDung { get; set; }
    }
}
